dist: bionic
addons:
 apt:
  packages: [doxygen, graphviz]
language: python
python:
  - "3.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip3 install --upgrade pip
  - pip3 install setuptools
  - pip3 install Sphinx
  - pip3 install platformio
  - platformio update

script:
  - make -C test
  - make -C docs html linkcheck
  - git diff --exit-code

notifications:
  email:
    recipients:
      - secure: "OxD/Ru5ImpnQKUXbziJhBl5iAJBraJ3JI+VTS4Iv9I6o6ZukvrpogI3fO4HM0wINALJT24AR6KDpGrAjtO40zjZGI2mHx+kgJGCQ1ebn0Q4iWtgKa4tJuC0DATTh7XhyuI2PjK58Z3WohyPBC7lmU8wfBgGQuEYsxHs+WKddpCnZ4kpGTYSj8oIZUtu5pg6J0piuf9Hqq1wU8TaMpSMJu2nECL3ouGYswl7YzC6Z6N/e5yBvug86D5NM+wwI615UVYcU/Zy7qtazizKAlRgP6XZoAk0m4UGmfPmLTfXeoZ/8FzxCADc7TJJr+j6zvFC5vEa56ZLsTNkHaftWoJRAqtZMRU7YAhc6rMcvigvF8KeqWhwxeaFw6XTzVXyJ7OpMkQaWw/R2M2oVOIwpxanyWyxc6ojMDWAXT3WxUItvU5HKp/f1/LgnQO6n7RZlh52OOdPv93symd0C2f+Kv37TRCSpk13yBAPbr4Lz0WofP9+tsim9Yhkp97+uWP7LeKtoI2HsH6aSqQHWXevlSu41IxcejtU1+ywLi31SRNvah9GYVbaSOihomnsEDqGirmjmEpqLhYt0P3CRf89EAKJEmFE/j5g+HXtLmbmOBPr5L/kEUxJ5UxJKlMelRs1aLxyMy3L6urTOA1mR9XUxRa6Pf9Lb2Oe0V1KOPs1Bbq8EP6A="
